### ISSUE TITLE
ElderMap Keyword

### ISSUE THREAD

**Issue by GlenCFL** [Crymsius/Crymsius-filter#3]
This a heads up that there is a new keyword with this patch after all: ElderMap. These maps are the result of using the Elder's Orb in order to promote any map to Tier 16.

If you don't add support within your filter, then these maps will appear identically to whatever the base tier of the map is. For example, a tier one map shaped by an Elder's Orb into a tier 16 would appear to be a tier 1 map within your filter.

**Comment by Crymsius** [comment]
Thanks for the heads up. I saw the issue on reddit but waited for some clarification from GGG in order to fix it.
It'll be fixed in an update later today.

**Comment by Crymsius** [comment]
Fixed with latest commit
